Add built-in support for Oidc tokens
Huachao/vscode-restclient pull request #1282
Opened 2024-07-10 21:31 UTC by AlexF4Dev

The pull request adds support for OIDC access tokens. It uses PKCE flow to acquire tokens. The tokens are cached, and refresh token is used when access token is expired.

2024-07-25 02:54 UTC, Huachao commented
@AlexF4Dev please check these alerts

2024-07-30 20:28 UTC, AlexF4Dev commented
> @AlexF4Dev please check these alerts

The first alert is probably false positive, because this is not a webapp. I have fixed regex warnings.

2024-07-31 01:31 UTC, Huachao requested changes

2024-07-31 01:31 UTC, Huachao commented on src/common/constants.ts
> +export const OidcDescription = "Prompts to sign in to an Oidc provider  and adds the token to the request";
remove extra whitespace in description

2024-07-31 01:31 UTC, Huachao commented on src/utils/memoryCache.ts
> +    public  clear(): void {
remove extra whitespace between access modifier `public` and method name in this file

2024-07-31 01:31 UTC, Huachao commented on src/utils/auth/oidcClient.ts
> +          res.end(`Authorization Server Error:${JSON.stringify(authCodeResponse)}`);
@AlexF4Dev please resolve this

2024-07-31 16:10 UTC, AlexF4Dev commented
Trust nobody even IDP :-). I have added sanitizeHTML to prevent the script injection. Do we need support for DPOP/MTLS?  It could be used to access API's protected by FAPI.

2024-08-05 01:30 UTC, Huachao approved these changes

2024-08-05 01:34 UTC, merged

2024-08-05 01:34 UTC, Huachao commented
@AlexF4Dev Merged, thanks

2025-03-16 09:40 UTC, noeldamps commented
@AlexF4Dev We handle the authorization with Keycloak. Have you maybe tried this feature with Keycloak? I only get an error that there is no valit http token. :/